config/routes.rb
UtilitiesApp::Application.routes.draw do
  resources :payment_methods

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users do
    member do
      get :payment_methods
    end
  end
  resources :utilities

  namespace :home do
    put :pay_utility
  end

  authenticated :user do
    root :controller => :home, :action => :index
  end
  devise_scope :user do
    root to: "devise/registrations#new"
  end

end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  attr_accessible :cardholders_name, :cc_number, :cc_security_code, :experation_date, :payment_type, :user_id
  validates :cc_number, presence: true
  validates :cc_security_code, presence: true

  belongs_to :user

  def select_box_display
    "Credit card ending in #{cc_number.last(4)}"
  end

  def obfuscated
    "XXXX-XXXX-XXXX-#{cc_number.last(4)}"
  end
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  # GET /payment_methods
  # GET /payment_methods.json
  def index
    @payment_methods = PaymentMethod.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payment_methods }
    end
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.json
  def show
    @payment_method = PaymentMethod.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment_method }
    end
  end

  # GET /payment_methods/new
  # GET /payment_methods/new.json
  def new
    @payment_method = PaymentMethod.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment_method }
    end
  end

  # GET /payment_methods/1/edit
  def edit
    @payment_method = PaymentMethod.find(params[:id])
  end

  # POST /payment_methods
  # POST /payment_methods.json
  def create
    @payment_method = PaymentMethod.new(params[:payment_method])
    @payment_method.user = current_user

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to payment_methods_path, notice: 'Payment method was successfully created.' }
        format.json { render json: @payment_method, status: :created, location: @payment_method }
      else
        format.html { render action: "new" }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /payment_methods/1
  # PUT /payment_methods/1.json
  def update
    @payment_method = PaymentMethod.find(params[:id])

    respond_to do |format|
      if @payment_method.update_attributes(params[:payment_method])
        format.html { redirect_to payment_methods_path, notice: 'Payment method was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.json
  def destroy
    @payment_method = PaymentMethod.find(params[:id])
    @payment_method.destroy

    respond_to do |format|
      format.html { redirect_to payment_methods_url, notice: "#{@payment_method.select_box_display} was successfully deleted." }
      format.json { head :no_content }
    end
  end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/_form.html.haml
= simple_form_for(@payment_method, :html => { :class => 'form-vertical' }) do |f|
  = f.error_notification
  = f.input :payment_type, selected: ["Credit Card"], collection: ["Credit Card"], label: "Payment Type"
  = f.input :cardholders_name, input_html: { :value => current_user.name }, label: "Cardholder's Name"
  = f.input :cc_number, :input_html => {:maxlength => 16}, label: "Credit Card Number"
  = f.input :cc_security_code, :input_html => {:maxlength => 3, :style => 'width: 70px'}, label: "Credit Card CVV Code"
  = f.input :experation_date, as: :date, start_year: Date.today.year, end_year: Date.today.year + 5, discard_day: true, add_month_numbers: true, order: [:month, :year], :input_html => {:style => 'width: 120px; float: left;'}, label: "Expiration Date"
  %br
  %br
  %br
  = f.button :submit, "Save", class: "btn btn-primary"
  = link_to 'Cancel', payment_methods_path, class: "btn btn-default"

app/views/payment_methods/edit.html.haml
%h1 Editing Payment Method
.row
  .col-md-5
    = render "form"

app/views/payment_methods/index.html.haml
- if !notice.blank?
  .alert.alert-success= notice
%h1 Payment Methods
.well.well-sm
  Use this tab to add, edit, or remove your payment information. If you choose to enter multiple credit cards, you will have the ability to associate a utility service with any one of the cards!
- if current_user.payment_methods.blank?
  %em You currently do not have any payment methods
- current_user.payment_methods.each do |payment_method|
  .row
    .col-md-4
      .user-field.bold Payment Type
    .col-md-4
      .user-field= payment_method.payment_type
    .col-md-4
      = link_to "Edit", edit_payment_method_path(payment_method), class: "btn btn-default btn-sm"
      = link_to "Delete", payment_method_path(payment_method), class: "btn btn-danger btn-sm", method: :delete
  .row
    .col-md-4
      .user-field.bold Carholder's Name
    .col-md-4
      .user-field= payment_method.cardholders_name
  .row
    .col-md-4
      .user-field.bold Credit Card Number
    .col-md-4
      .user-field= payment_method.obfuscated
  .row
    .col-md-4
      .user-field.bold Credit Card CVV Code
    .col-md-4
      .user-field= payment_method.cc_security_code
  .row
    .col-md-4
      .user-field.bold Expiration Date
    .col-md-4
      - if payment_method.experation_date
        .user-field= payment_method.experation_date.strftime('%m/%Y')
  %hr
%br
= link_to "Add New Payment Method", new_payment_method_path, class: "btn btn-default margin-top-20"
/ = link_to 'Edit', edit_user_path(user_id: @user, payment_edit: true), class: "btn btn-default margin-top-20"


/ <%= link_to 'New Payment method', new_payment_method_path %>

app/views/payment_methods/new.html.haml
%h1 New Payment Method
.row
  .col-md-5
    = render "form"

app/views/payment_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Payment type:</b>
  <%= @payment_method.payment_type %>
</p>

<p>
  <b>Cardholders name:</b>
  <%= @payment_method.cardholders_name %>
</p>

<p>
  <b>Cc number:</b>
  <%= @payment_method.cc_number %>
</p>

<p>
  <b>Cc security code:</b>
  <%= @payment_method.cc_security_code %>
</p>

<p>
  <b>Experation date:</b>
  <%= @payment_method.experation_date %>
</p>


<%= link_to 'Edit', edit_payment_method_path(@payment_method) %> |
<%= link_to 'Back', payment_methods_path %>