config/routes.rb
UtilitiesApp::Application.routes.draw do
  resources :payment_methods

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users do
    member do
      get :payment_methods
    end
  end
  resources :utilities

  namespace :home do
    put :pay_utility
  end

  authenticated :user do
    root :controller => :home, :action => :index
  end
  devise_scope :user do
    root to: "devise/registrations#new"
  end

end

app/models/utility.rb
class Utility < ActiveRecord::Base
  attr_accessible :name, :account_number, :user_id, :payment_method_id

  belongs_to :payment_method

  validates :name, :account_number, presence: true

  def self.has_unpaid_bills(user)
    unpaid_bills = false
    user.utilities.each do |utility|
      unpaid_bills = unpaid_bills || !utility.paid
    end
    unpaid_bills
  end
end

app/controllers/utilities_controller.rb
class UtilitiesController < ApplicationController
  # GET /utilities
  # GET /utilities.json
  def index
    @utilities = current_user.utilities

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @utilities }
    end
  end

  # GET /utilities/1
  # GET /utilities/1.json
  def show
    @utility = Utility.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @utility }
    end
  end

  # GET /utilities/new
  # GET /utilities/new.json
  def new
    @utility = Utility.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @utility }
    end
  end

  # GET /utilities/1/edit
  def edit
    @utility = Utility.find(params[:id])
  end

  # POST /utilities
  # POST /utilities.json
  def create
    @utility = Utility.new(params[:utility])

    respond_to do |format|
      if @utility.save
        format.html { redirect_to utilities_path, notice: 'Utility was successfully created.' }
        format.json { render json: @utility, status: :created, location: @utility }
      else
        format.html { render action: "new" }
        format.json { render json: @utility.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /utilities/1
  # PUT /utilities/1.json
  def update
    @utility = Utility.find(params[:id])

    respond_to do |format|
      if @utility.update_attributes(params[:utility])
        format.html { redirect_to utilities_path, notice: 'Utility was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @utility.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utilities/1
  # DELETE /utilities/1.json
  def destroy
    @utility = Utility.find(params[:id])
    @utility.destroy

    respond_to do |format|
      format.html { redirect_to utilities_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/utilities_helper.rb
module UtilitiesHelper
end

app/views/utilities/_form.html.haml
= simple_form_for(@utility, :html => { :class => 'form-horizontal' }) do |f|
  / = f.error_notification
  - if !@utility.errors.blank?
    .alert.alert-danger
      - @utility.errors.each do |error|
        %p 
          Please provide the 
          = error
  = f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }
  = f.input :name, label: "Provider", collection: [ "NStar", "National Grid", "Comcast"]
  .service-label Name
  .service-field= current_user.name
  .service-label Address
  .service-field= current_user.address
  - if !current_user.city.blank?
    = succeed ',' do
      = current_user.city
  = current_user.state
  = current_user.zip

  .service-label 
    Account Number
    %button.btn.btn-default.overlay.example-button.margin-bottom-4{ type: "button", data: { container: "body", toggle: "popover", placement: "left", content: "Vivamus sagittis lacus vel augue laoreet rutrum faucibus." }}
      Where do I find this?
      .glyphicon.glyphicon-question-sign
  = f.input :account_number, label: false
  .service-label Email
  .service-field= current_user.email
  .service-label Payment Method
  = f.collection_select :payment_method_id, current_user.payment_methods, :id, :select_box_display, {}, {:class => "select optional form-control", :selected => @utility.payment_method}
  %br
  .service-field.row
    .col-md-6
      Payment Type: 
    .col-md-6.selected_payment_type
      / # = current_user.payment_type
  .service-field.row
    .col-md-6
      Cardholder's Name: 
    .col-md-6.selected_cardholders_name
      / # = current_user.cardholders_name
  .service-field.row
    .col-md-6
      Card Number: 
    .col-md-6.selected_cc_number
      xxxx-xxxx-xxxx-
      / # = current_user.cc_number.last(4)
  .service-field.row
    .col-md-6
      Exp. Date: 
    .col-md-6.selected_exp_date
      / # = current_user.experation_date.strftime('%m/%Y')

  %br
  %br
  = f.button :submit, "Save", class: "btn btn-primary"
  = link_to 'Cancel', utilities_path, class: "btn btn-default"

app/views/utilities/edit.html.haml
#utilities
  %h1 Edit Service
  .row
    .col-md-5
      = render 'form'

app/views/utilities/index.html.haml
%h1 Services
.well.well-sm
  Use this tab to add, edit, or remove a current utility service. You’ll need your account number for the utility service, so be sure to have your last paper bill nearby!
- if notice
  .alert.alert-success= notice
- if @utilities.blank?
  %em You currently have no services saved
- else
  %table.table.table-striped
    %tr
      %th Name
      %th Account Number
      %th
      %th
      %th For Demo
    - @utilities.each do |utility|
      %tr
        %td= utility.name
        %td= utility.account_number
        %td= link_to 'Edit', edit_utility_path(utility), class: "btn btn-default"
        %td= link_to 'Delete', utility, method: :delete, class: "btn btn-danger font-white", data: { confirm: 'Are you sure?' }
        - if utility.paid
          %td= link_to "Reset payment", home_pay_utility_path(id: utility.id, paid: false), method: :put
        - else
          %td
%br
= link_to 'Add New Service', new_utility_path, class: "btn btn-default margin-top-20"

app/views/utilities/new.html.haml
#utilities
  %h1 New Service
  - if !current_user.has_basic_info
    .alert.alert-warning 
      You have not completed filling out your basic information. Please first 
      = link_to "Complete account", edit_user_path(current_user)
  - elsif current_user.payment_methods.blank?
    .alert.alert-warning 
      You have not completed filling out a payment method. Please first 
      = link_to "Add a payment method", new_payment_method_path
  - else
    .row
      .col-md-5
        = render 'form'

app/views/utilities/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_utility_path(@utility) %> |
<%= link_to 'Back', utilities_path %>