config/routes.rb
UtilitiesApp::Application.routes.draw do
  resources :payment_methods

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users do
    member do
      get :payment_methods
    end
  end
  resources :utilities

  namespace :home do
    put :pay_utility
  end

  authenticated :user do
    root :controller => :home, :action => :index
  end
  devise_scope :user do
    root to: "devise/registrations#new"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :city, :address, :state, :zip, :phone_number

  has_many :utilities
  has_many :payment_methods

  # def has_payment_method
  #   !(payment_type.blank? && carholders_name.blank? && cc_number.blank? && cc_security_code.blank? && experation_date.blank?)
  # end

  def has_basic_info
    !(name.blank? && city.blank? && address.blank? && state.blank? && zip.blank? && phone_number.blank?)
  end

  # account has 8 fields including email and password
  def account_completion
    res = 2
    res = res + 1 if !name.blank?
    res = res + 1 if !city.blank?
    res = res + 1 if !address.blank?
    res = res + 1 if !state.blank?
    res = res + 1 if !zip.blank?
    res = res + 1 if !phone_number.blank?
    res # res will be res/8 when looking to get the percentage
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @payments = false

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  def payment_methods
    @payments = true
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @payment_edit = params[:payment_edit]
    @payments = params[:payment_edit]
  end


  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        if params[:payment_edit]
          format.html { redirect_to payment_methods_user_path(@user), notice: 'Your payment methods were successfully updated.' }
        else
          format.html { redirect_to @user, notice: 'Your account was successfully updated.' }
        end
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/views/users/edit.html.haml
%h1 Editing Account
.row
  .col-md-5
    = simple_form_for(@user) do |f|
      = f.error_notification
      = f.input :name
      = f.input :address
      = f.input :city
      = f.input :state
      = f.input :zip, :input_html => { :maxlength => 5, class: "zip-input" }
      = f.input :phone_number, label: "Phone Number", :input_html => { :maxlength => 10, class: "phone-input" }
    
      %br
      = f.button :submit, "Save", class: "btn btn-primary"
      = link_to 'Cancel', user_path, class: "btn btn-default"

app/views/users/index.html.erb
<h1>Listing payment_methods</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payment_methods.each do |payment_method| %>
  <tr>
    <td><%= link_to 'Show', payment_method %></td>
    <td><%= link_to 'Edit', edit_payment_method_path(payment_method) %></td>
    <td><%= link_to 'Destroy', payment_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment method', new_payment_method_path %>

app/views/users/new.html.erb
<h1>New payment_method</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_methods_path %>

app/views/users/payment_methods.html.haml
- if !notice.blank?
  .alert.alert-success= notice
%h1 Payment Methods
.row
  .col-md-4
    .user-field.bold Payment Type
  .col-md-4
    .user-field= current_user.payment_type
.row
  .col-md-4
    .user-field.bold Carholder's Name
  .col-md-4
    .user-field= current_user.carholders_name
.row
  .col-md-4
    .user-field.bold Credit Card Number
  .col-md-4
    .user-field= current_user.cc_number
.row
  .col-md-4
    .user-field.bold Credit Card CVV Code
  .col-md-4
    .user-field= current_user.cc_security_code
.row
  .col-md-4
    .user-field.bold Expiration Date
  .col-md-4
    - if current_user.experation_date
      .user-field= current_user.experation_date.strftime('%m/%Y')
= link_to 'Edit', edit_user_path(user_id: @user, payment_edit: true), class: "btn btn-default margin-top-20"

app/views/users/show.html.haml
- if !notice.blank?
  .alert.alert-success= notice
%h1 Account
.well.well-sm
  Use this tab to update your personal information. Be sure to use your billing information associated with your utility service!
= render "home/account_completion_widget"
.row
  .col-md-4
    .user-field.bold Name
  .col-md-4
    .user-field= @user.name 
.row
  .col-md-4
    .user-field.bold Email
  .col-md-4
    .user-field= @user.email   
.row
  .col-md-4
    .user-field.bold City
  .col-md-4
    .user-field= @user.city
.row
  .col-md-4
    .user-field.bold Address
  .col-md-4
    .user-field= @user.address
.row
  .col-md-4
    .user-field.bold State
  .col-md-4
    .user-field= @user.state
.row
  .col-md-4
    .user-field.bold Zip
  .col-md-4
    .user-field= @user.zip
.row
  .col-md-4
    .user-field.bold Phone Number
  .col-md-4
    .user-field= @user.phone_number

= link_to 'Edit', edit_user_path(@user), class: "btn btn-default margin-top-20"