config/routes.rb
UtilitiesApp::Application.routes.draw do
  resources :payment_methods

  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users do
    member do
      get :payment_methods
    end
  end
  resources :utilities

  namespace :home do
    put :pay_utility
  end

  authenticated :user do
    root :controller => :home, :action => :index
  end
  devise_scope :user do
    root to: "devise/registrations#new"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @utilities = current_user.utilities
  end

  def pay_utility
    @utility = Utility.find(params[:id])
    @utility.update_attribute(:paid, params[:paid])

    respond_to do |format|
      if params[:paid] == "true"
        format.html { redirect_to root_path, notice: "Your #{@utility.name} bill of $52.37 has been successfully paid!" }
      else
        format.html { redirect_to utilities_path, notice: 'For Demo: You have reset the payment for your bill' }
      end
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_account_completion_widget.html.haml
- if current_user.account_completion != 8
  .alert.alert-info{ role: "alert" }
    .progress.progress-striped.active
      .progress-bar.progress-bar-striped{"data-transitiongoal" => (current_user.account_completion/8.0)*100, :role => "progressbar"}
    Your account info is not yet complete!
    = link_to "Click here", edit_user_path(current_user)
    to finish filling out your account.

app/views/home/index.html.haml
%h1 
  Pending Bills
  - if (unpaid_bills = @utilities.select{|u| !u.paid}.size) > 0
    %span.bold (#{unpaid_bills})
= render "account_completion_widget"
- if notice
  .alert.alert-success= notice
- if @utilities.blank?
  .well.well-sm
    Welcome to Utilitizer! This application is a powerful tool that allows you to pay all of your online bills on one, single site. You have signed in with the following email address: 
    %b #{current_user.email}.
    On your left, you’ll see several tabs.
    %ul
      %li 
        Use the 
        = link_to "Services", utilities_path
        tab to add a new utility service or update a current utility service. 
      %li 
        Use the 
        = link_to "Account", user_path(current_user.id)
        tab to update your personal information.
      %li 
        Use the 
        = link_to "Payment Methods", payment_methods_path
        tab to add and update your payment information.
- elsif Utility.has_unpaid_bills(current_user)
  - @utilities.each do |utility|
    - if !utility.paid?
      .well.well-sm.row.payment-due
        %h4= utility.name
        .col-md-6
          .row
            .col-md-5
              Account Number:
            .col-md-6
              = utility.account_number
            .col-md-5
              Contact Email:
            .col-md-6
              = current_user.email
            .col-md-5
              Pay Method:
            .col-md-6
              - if utility.payment_method.blank?
                .bold
                  You have removed the payment method. Please 
                  = link_to "add a payment method", new_payment_method_path, class: "blue-link"
                  and 
                  = link_to "edit the service", edit_utility_path(utility), class: "blue-link"
              - else
                = utility.payment_method.payment_type
                %span ending in
                %span= utility.payment_method.cc_number.last(4)
                %span= link_to "Change Method", edit_utility_path(utility), class: "blue-link"
        .col-md-4
          .row
            .col-md-5
              Amount:
            .col-md-6.red.bold
              $52.37
            .col-md-5
              Due Date:
            .col-md-6
              = (Time.now + 10.days).strftime('%m/%d/%Y')
        .col-md-2
          = button_tag "Pay Now", class: "#{'disabled' if utility.payment_method.blank?} btn btn-success font-white", data: { toggle: "modal", target: "#confirm-payment-modal" }
    #confirm-payment-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "confirm-payment-modal-label", :role => "dialog", :tabindex => "-1"}
      .modal-dialog
        .modal-content
          .modal-header
            %button.close{"data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×
              %span.sr-only Close
            %h4#confirm-payment-modal-label.modal-title Confirmation
          .modal-body
            - payment_method =  (utility.payment_method && utility.payment_method.select_box_display) || 0
            A payment of 
            %b $52.37 
            will be sent to #{utility.name} using #{payment_method}.
          .modal-footer
            %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cancel
            = link_to "Pay Now", home_pay_utility_path(id: utility.id, paid: true), method: :put, class: "btn btn-success font-white"
- else
  %em You currently do not have any bills that need to be paid.
#calendar.margin-top-20.margin-bottom-20